#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-SQL-Tokenizer
Version  : 0.24
Release  : 15
URL      : https://cpan.metacpan.org/authors/id/I/IZ/IZUT/SQL-Tokenizer-0.24.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/I/IZ/IZUT/SQL-Tokenizer-0.24.tar.gz
Summary  : A simple SQL tokenizer.
Group    : Development/Tools
License  : Artistic-1.0
Requires: perl-SQL-Tokenizer-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
SQL-Tokenizer
This module is a simple regular expressions based SQL tokenizer. It
was created to make DBIx::Placeholder::Named possible.

%package dev
Summary: dev components for the perl-SQL-Tokenizer package.
Group: Development
Provides: perl-SQL-Tokenizer-devel = %{version}-%{release}
Requires: perl-SQL-Tokenizer = %{version}-%{release}

%description dev
dev components for the perl-SQL-Tokenizer package.


%package perl
Summary: perl components for the perl-SQL-Tokenizer package.
Group: Default
Requires: perl-SQL-Tokenizer = %{version}-%{release}

%description perl
perl components for the perl-SQL-Tokenizer package.


%prep
%setup -q -n SQL-Tokenizer-0.24
cd %{_builddir}/SQL-Tokenizer-0.24

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/SQL::Tokenizer.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
